name: Build Spigot Plugin

on:
  push:
    branches:
      - master  # Trigger build when changes are pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload Jar to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: maceplugin-jar
        path: target/*.jar
